FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN useradd --create-home appuser

COPY requirements.txt .

RUN apt-get update \
 && apt-get install -y --no-install-recommends gcc libc-dev \
 && pip install --no-cache-dir -r requirements.txt \
 && apt-get remove -y gcc libc-dev \
 && apt-get autoremove -y \
 && rm -rf /var/lib/apt/lists/*

# Copy application, train, run_pipeline.sh and research_centers.csv
COPY train.py .
COPY app.py .
COPY run_pipeline.sh .
COPY research_centers.csv .

RUN chmod +x run_pipeline.sh

# Set ownership
RUN chown -R appuser /app

USER appuser

CMD ["./run_pipeline.sh"]